### ISSUE TITLE
Issue with embedded HTML documents containing equations

### ISSUE THREAD

**Issue by gueyenono** [JohnCoene/awn#2]
First and foremost, thank you very much for this awesome addition to the Coene-verse.

I found that there is something odd that happens when embedding an HTML document that contains equations inside a modal. Even though `{awn}` does not seem to support Mathjax at this point, I managed to display my equations inside a modal using the fairly recent [katex](https://github.com/ropensci/katex/) package. However, there's a JavaScript comment, which appears at the bottom of the modal. The JS comment does NOT appear when the HTML file is rendered outside the modal. I suspect that the odd thing that happens may be due to `{awn}` and `{katex}` having some sort of clash. Here is a picture that shows the issue.

![awn-katex-issue](https://user-images.githubusercontent.com/8573955/130015528-64f4d69a-9e2c-439b-98fa-28fe6a1df9cb.png)

And now, the mandatory minimal reproducible example, which contains 2 files: `document.Rmd` (which is knit to an HTML document) and `app.R`

**document.Rmd**

~~~markdown
---
title: "Help file"
output: 
  html_document:
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(katex)
```

## Linear regression

The matrix formula of the OLS estimator is:

```{r}
tex1 <- "\\frac{1}{\\Bigl(\\sqrt{\\phi \\sqrt{5}}-\\phi\\Bigr) e^{\\frac{2}{5} \\pi}} \\equiv 1+\\frac{e^{-2\\pi}} {1+\\frac{e^{-4\\pi}} {1+\\frac{e^{-6\\pi}} {1+\\frac{e^{-8\\pi}} {1+\\cdots} } } }"
katex_html(tex1, include_css = TRUE, output = "html")
```

$$
y_t = \alpha + \beta x_t + \varepsilon_t
$$
~~~~

**app.R**

~~~markdown
library(awn)
library(shiny)

ui <- fluidPage(
  useAwn(),
  actionButton("show", "Show"),
  actionButton("show2", "Show")
)

server <- function(input, output, session) {
  
  observeEvent(input$show, {
    modal(
      h1(shiny::HTML("Hello <b>{awn}</b>!"))
    )
  })
  
  observeEvent(input$show2, {
    modal(
      shiny::includeHTML("www/document.html")
    )
  })
  
}

shinyApp(ui, server)
~~~

**Comment by JohnCoene** [comment]
coene-verse, I love it! :)

This works for me, does it do what you want or must it use `includeHTML`?

```r
tex1 <- "\\frac{1}{\\Bigl(\\sqrt{\\phi \\sqrt{5}}-\\phi\\Bigr) e^{\\frac{2}{5} \\pi}} \\equiv 1+\\frac{e^{-2\\pi}} {1+\\frac{e^{-4\\pi}} {1+\\frac{e^{-6\\pi}} {1+\\frac{e^{-8\\pi}} {1+\\cdots} } } }"
rendered <- katex::katex_html(tex1, include_css = TRUE, output = "html", preview = FALSE)

library(awn)
library(shiny)

ui <- fluidPage(
  useAwn(),
  actionButton("show", "Show"),
  actionButton("show2", "Show")
)

server <- function(input, output, session) {
  
  observeEvent(input$show, {
    modal(
      h1(shiny::HTML("Hello <b>{awn}</b>!"))
    )
  })
  
  observeEvent(input$show2, {
    modal(
      rendered
    )
  })
  
}

shinyApp(ui, server)
```

**Comment by gueyenono** [comment]
Actually, my goal is to embed a whole HTML document inside the modal. It's a kind of help file whenever the user of my app clicks on a button. And the document contains `{katex}` equations.

**Comment by etiennebacher** [comment]
The javascript message disappears if you replace `html_document` by `html_fragment` in `document.Rmd`. The last equation is not rendered because apparently mathjax is not supported by `awn` for now.

**Comment by gueyenono** [comment]
Thank you @etiennebacher for the solution. I'll close this issue.

**Comment by JohnCoene** [comment]
I just pushed a small change so you can run a callback function when the modal is shown.

```r
library(awn)
library(shiny)

# Get MathJax dependency
deps <- withMathJax()[[1]]

ui <- fluidPage(
  useAwn(),
  deps, # include dependency
  actionButton("show", "Show")
)

server <- function(input, output, session) {
  
  observeEvent(input$show, {
    modal(
      helpText("Some math here $$\\alpha+\\beta$$"),
      # when the modal is shown we run the javascript to display
      # the equation 
      .onShown = "MathJax.Hub.Queue([\"Typeset\", MathJax.Hub]);"
    )
  })
  
}

shinyApp(ui, server)
```

This should make all mathjax equations work

**Comment by gueyenono** [comment]
It works perfectly @JohnCoene 
Thanks again to you both for your prompt answers.
